-- PHASE 4 BATCH 1 — CMS foundation models (Episode, NewsArticle, Event) plus
-- an additive, nullable RsvpSubmission.eventId relation.
--
-- HOW THIS FILE WAS PRODUCED (read before applying): normally this would be
-- generated by `prisma migrate dev` diffing schema.prisma against the real
-- database's current migration history. That could not be done here —
-- `prisma migrate dev` is explicitly forbidden against production by this
-- batch's own instructions, and separately, the sandbox this was written in
-- has no network path to binaries.prisma.sh/objects.prisma.sh at all (the
-- schema-engine binary fetch returns 403; reconfirmed while preparing this
-- batch, same as every previous batch that touched Prisma). So this SQL was
-- hand-written to match Prisma's own Postgres migration conventions
-- (table/column/constraint/index naming, TEXT for String, TIMESTAMP(3) for
-- DateTime) rather than generated and verified by the CLI.
--
-- Why this is still safe to apply: every statement below is purely additive
-- — three new CREATE TABLEs, and one nullable ADD COLUMN + one FK on the
-- existing RsvpSubmission table. Nothing here touches, renames, or drops any
-- existing table, column, or row, so it does not depend on knowing the
-- exact contents of whatever migration originally created ContactSubmission
-- / MinisterQuestion / NewsletterSubscriber / RsvpSubmission in the real
-- database — it only needs those tables (RsvpSubmission specifically) to
-- already exist, which they do.
--
-- Before running this against production: apply it with
-- `prisma migrate deploy` (never `migrate dev`, per this batch's own
-- instructions), which only ever applies pending migrations in order and
-- refuses outright on any real incompatibility — it does not silently
-- partially-apply or corropt existing data. This was not run against
-- production by the agent that wrote it.

-- CreateTable
CREATE TABLE "Episode" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "summary" TEXT NOT NULL,
    "episodeNumber" INTEGER,
    "guestName" TEXT,
    "guestTitle" TEXT,
    "durationSeconds" INTEGER,
    "coverImageUrl" TEXT,
    "audioUrl" TEXT,
    "videoUrl" TEXT,
    "spotifyUrl" TEXT,
    "applePodcastsUrl" TEXT,
    "youtubeUrl" TEXT,
    "transcript" TEXT,
    "status" TEXT NOT NULL DEFAULT 'draft',
    "publishedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Episode_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "NewsArticle" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "summary" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "featuredImageUrl" TEXT,
    "status" TEXT NOT NULL DEFAULT 'draft',
    "publishedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "NewsArticle_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Event" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "location" TEXT,
    "startsAt" TIMESTAMP(3) NOT NULL,
    "endsAt" TIMESTAMP(3),
    "coverImageUrl" TEXT,
    "status" TEXT NOT NULL DEFAULT 'draft',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Event_pkey" PRIMARY KEY ("id")
);

-- AlterTable (additive only — existing columns/rows untouched)
ALTER TABLE "RsvpSubmission" ADD COLUMN "eventId" TEXT;

-- CreateIndex
CREATE UNIQUE INDEX "Episode_slug_key" ON "Episode"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "Episode_episodeNumber_key" ON "Episode"("episodeNumber");

-- CreateIndex
CREATE INDEX "Episode_status_idx" ON "Episode"("status");

-- CreateIndex
CREATE INDEX "Episode_publishedAt_idx" ON "Episode"("publishedAt");

-- CreateIndex
CREATE UNIQUE INDEX "NewsArticle_slug_key" ON "NewsArticle"("slug");

-- CreateIndex
CREATE INDEX "NewsArticle_status_idx" ON "NewsArticle"("status");

-- CreateIndex
CREATE INDEX "NewsArticle_publishedAt_idx" ON "NewsArticle"("publishedAt");

-- CreateIndex
CREATE UNIQUE INDEX "Event_slug_key" ON "Event"("slug");

-- CreateIndex
CREATE INDEX "Event_status_idx" ON "Event"("status");

-- CreateIndex
CREATE INDEX "Event_startsAt_idx" ON "Event"("startsAt");

-- CreateIndex
CREATE INDEX "RsvpSubmission_eventId_idx" ON "RsvpSubmission"("eventId");

-- AddForeignKey
-- ON DELETE SET NULL: if an Event row is ever deleted, RSVP submissions
-- that reference it are preserved (eventId reverts to null) rather than
-- being deleted themselves — RSVP submissions are administrative data and
-- must never be silently destroyed as a side effect of an unrelated
-- change. This is Prisma's own default referential action for an optional
-- (nullable) relation, not a deviation from it.
ALTER TABLE "RsvpSubmission" ADD CONSTRAINT "RsvpSubmission_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "Event"("id") ON DELETE SET NULL ON UPDATE CASCADE;
